In [3]:
from deep_kolmogorov import modeling, pdes, trainer
import torch
import numpy as np

In [281]:
import importlib
importlib.reload(trainer)
pde = pdes.BSasian()
import numpy as np
K = 100
num_path = 10000
device = torch.device("cuda")
config = {"s":10, "r":0.02, "sigma": 0.3, "kappa": 1.01}

import importlib
importlib.reload(pdes)
pde = pdes.BSasian()

with torch.no_grad(): 
    data = {
        key: torch.full(((K+1)*num_path, 1), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
            "t": torch.full((K + 1,), 0.6, dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = torch.concat([data["s"], data["s"]], dim=1)
data["K"] = pdes.BSasian.get_K(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

print("exact price: ", (torch.exp(-data["t"]*data["r"]) * pde.solution(data))[0,0])

n is 250
Estimated price:  tensor(0.1235, device='cuda:0')
Estimated CI:  [0.12306501716375351, 0.12392885237932205]
exact price:  tensor(0.1234, device='cuda:0')


In [133]:
0.001/0.067

0.014925373134328358

In [126]:
d1

-0.03299873109647069

In [127]:
d2

-0.03317193617722758

In [33]:
import importlib
importlib.reload(trainer)
pde = pdes.BSTI()
import numpy as np
K = 100
num_path = 10000
device = torch.device("cuda")
config = {"s":10, "r0":0.02, "r1":2, "r2":2, "sigma_bar": 0.3, "beta":0.02, "kappa": 1.01}

import importlib
importlib.reload(pdes)
pde = pdes.BSTI()

with torch.no_grad(): 
    data = {
        key: torch.full(((K+1)*num_path, 1), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
            "t": torch.full((K + 1,), 0.1, dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = data["s"].clone()
data["K"] = pdes.BSTI.get_K(data)
data["r"] = pdes.BSTI.get_r(data)
data["sigma"] = pdes.BSTI.get_sigma(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

print("exact price: ", (torch.exp(-pde.get_rmt(0, data["t"], data["r0"], data["r1"], data["r2"])) * pde.solution(data))[0,0])

Estimated price:  tensor(8.0087, device='cuda:0')
Estimated CI:  [8.003179550170898, 8.014310836791992]
exact price:  tensor(8.0043, device='cuda:0')


In [208]:
0.01/0.74

0.008620689655172415

In [143]:
pde.get_rmt(0, data["t"], data["r0"], data["r1"], data["r2"])[0,0]

tensor(99.9000, device='cuda:0')

In [41]:
import importlib
importlib.reload(trainer)
import numpy as np
K = 100
num_path = 10000
device = torch.device("cuda")
config = {"s":10, "r0":0.02, "r1":0.002, "r2":0.02, "sigma_bar": 0.3, "beta":0.02, "rho": 0.1, "kappa": 1.01}

import importlib
importlib.reload(pdes)
pde = pdes.BSbasketTI()

with torch.no_grad(): 
    data = {
        key: torch.full(((K+1)*num_path,  pde.hypercubes[key].dims[0]), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
            "t": torch.full((K + 1,), 0.1, dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = data["s"].clone()
data["K"] = pdes.BSbasketTI.get_K(data)
data["r"] = pdes.BSbasketTI.get_r(data)
# data["sigma"] = pdes.BSbasketTI.get_sigma(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

print("exact price: ", (torch.exp(-pde.get_rmt(0, data["t"], data["r0"], data["r1"], data["r2"])) * pde.solution(data))[0,0])

Estimated price:  tensor(0.4012, device='cuda:0')
Estimated CI:  [0.39986756443977356, 0.40257909893989563]
exact price:  tensor(0.4014, device='cuda:0')


In [7]:
import importlib
importlib.reload(trainer)
pde = pdes.MJD()
import numpy as np
K = 1000
num_path = 100000
device = torch.device("cuda")
config = {"s":10, "r":0.02, "sigma": 0.3, "kappa": 1.01, "lambda":20, "m" : 0.02, "delta": 0.05}

import importlib
importlib.reload(pdes)
pde = pdes.MJD()

with torch.no_grad():
    data = {
        key: torch.full(((K+1)*num_path, 1), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
            "t": torch.full((K + 1,), 0., dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = data["s"]
data["K"] = pdes.MJD.get_K(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)

print("exact price: ", (torch.exp(-data["t"]*data["r"]) * pde.solution(data))[0,0])
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

exact price:  tensor(1.5750, device='cuda:0')
Estimated price:  tensor(1.5755, device='cuda:0')
Estimated CI:  [1.5749592781066895, 1.5761103630065918]


In [8]:
#Merton Jump Diffusion- Analytical and Simulation vs Black Scholes

import math as math
import numpy as np

def sn_cdf(x):
    a1 =  0.254829592
    a2 = -0.284496736
    a3 =  1.421413741
    a4 = -1.453152027
    a5 =  1.061405429
    p  =  0.3275911

    sign = 1
    if x < 0:
        sign = -1
    x = abs(x)/math.sqrt(2.0)

    t = 1.0/(1.0 + p*x)
    y = 1.0 - (((((a5*t + a4)*t) + a3)*t + a2)*t + a1)*t*math.exp(-x*x)

    return 0.5*(1.0 + sign*y)


def BS_call(S0,sig, tau,r, K):
    print(r)
    d1=math.log(S0/K)+(r+0.5*sig*sig)*tau
    d1/=(sig*math.sqrt(tau))
    d2=d1-sig*math.sqrt(tau)

    price=S0*sn_cdf(d1)-K*math.exp(-r*tau)*sn_cdf(d2)
    print(S0)
    print(d1)
    print(K)
    print(price)
    print(S0*sn_cdf(d1))
    print(-K*math.exp(-r*tau)*sn_cdf(d2))
    print(-K*math.exp(-r*tau))
    print(sn_cdf(d2))
    return price

def merton_call(S0,sig, tau,r, K,lam,mu_y,sig_y, N):
    price=0.0
    k=math.exp(mu_y+0.5*sig_y*sig_y)-1
    for n in range(N):
        sig_n=math.sqrt( sig*sig+n*sig_y*sig_y/tau)
        S0_n=S0*math.exp(-lam*k*tau+n*mu_y+0.5*n*sig_y*sig_y)
        prob_n=(lam*tau)**n/math.factorial(n)*math.exp(-lam*tau)
        price+=BS_call(S0_n,sig_n, tau,r, K)*prob_n
    return price
        
def merton_call_alt(S0,sig, tau,r, K,lam,mu_y,sig_y, N):
    price=0.0
    k=math.exp(mu_y+0.5*sig_y*sig_y)-1
    lam_b=lam*(1.0+k)
    for n in range(N):
        sig_n=math.sqrt( sig*sig+n*sig_y*sig_y/tau)
        r_n=r-lam*k+n*(mu_y+0.5*sig_y*sig_y)/tau
        prob_n=(lam_b*tau)**n/math.factorial(n)*math.exp(-lam_b*tau)
        # print(price)
        # print(BS_call(S0,sig_n, tau,r_n, K))
        # print(prob_n)
        # print(r_n)
        # print
        # print(BS_call(S0,sig_n, tau,r_n, K)*prob_n)
        price+=BS_call(S0,sig_n, tau,r_n, K)*prob_n
    return price

def merton_call_simulation(S0,sig, tau,r, K,lam,mu_y,sig_y):
    nsim=100000
    k=math.exp(mu_y+0.5*sig_y*sig_y)-1
    price=0.0
    for i in range(nsim):
        jump_N=np.random.poisson(lam*tau)
        jump_normal=np.random.normal(mu_y,sig_y,jump_N)
        jump_sum=np.sum(jump_normal)
        S_tau=S0*math.exp((r-lam*k-0.5*sig*sig)*tau+sig*np.random.normal(0,math.sqrt(tau))+jump_sum)
        price+=max(S_tau-K,0)
    price*=math.exp(-r*tau)
    price/=nsim
    return price


# print(BS_call(100,0.4, 1,0.05, 100))
# print(merton_call(100,0.4, 1,0.05, 100,0.5, 0.1,0.1, 20))
print(merton_call_alt(10,0.3, 0.5,0.02, 10.1,20, 0,0.01, 100))
# print(merton_call_simulation(100,0.4, 1,0.05, 100,0.5, 0.1,0.1)) 

0.01899997499958282
10
0.10394307825108252
10.1
0.8426412476173013
5.413927942225504
-4.571286694608203
-10.004504447731685
0.45692285095086815
0.019099974999582818
10
0.10429865968267861
10.1
0.8438045303336379
5.41533883589234
-4.5715343055587025
-10.004004235014722
0.45697044884867294
0.019199974999582817
10
0.10465358160924179
10.1
0.8449667550887696
5.416747060550781
-4.571780305462012
-10.003504047307768
0.4570178893157353
0.01929997499958282
10
0.1050078470968694
10.1
0.8461279252621106
5.418152628481336
-4.572024703219226
-10.003003884609575
0.4570651732179824
0.01939997499958282
10
0.10536145918991098
10.1
0.8472880442147144
5.419555551877851
-4.5722675076631365
-10.00250374691889
0.4571123014146882
0.01949997499958282
10
0.10571442091117315
10.1
0.848447115289436
5.42095584284832
-4.572508727558884
-10.002003634234466
0.45715927475853746
0.01959997499958282
10
0.10606673526212206
10.1
0.8496051418110335
5.422353513415697
-4.572748371604663
-10.00150354655505
0.457206094095693

In [6]:
from deep_kolmogorov import modeling, pdes, trainer
import torch
import numpy as np
import importlib
importlib.reload(trainer)
pde = pdes.BSbasket()
import numpy as np
K = 1000
num_path = 1000
device = torch.device("cuda")
config_d = {"s":10, "sigma": 0.25}
config = {"r":0.0, "kappa": 0.5, "rho": 0.}

import importlib
importlib.reload(pdes)
pde = pdes.BSbasket()

with torch.no_grad():
    data = {
        key: torch.full(((K+1)*num_path, 1), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
        key: torch.full(((K+1)*num_path, 10), value, dtype=torch.float32, device=device) for key, value in config_d.items()
        }
    )
    data.update(
        {
            "t": torch.full((K + 1,), 0.9, dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = data["s"]
data["K"] = pdes.BSbasket.get_K(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)

print("exact price: ", (torch.exp(-data["t"]*data["r"]) * pde.solution(data))[0,0])
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

tensor([[9.9719],
        [9.9719],
        [9.9719],
        ...,
        [9.9719],
        [9.9719],
        [9.9719]], device='cuda:0')
tensor([[-5.],
        [-5.],
        [-5.],
        ...,
        [-5.],
        [-5.],
        [-5.]], device='cuda:0')
tensor([[9.9719],
        [9.9719],
        [9.9719],
        ...,
        [9.9719],
        [9.9719],
        [9.9719]], device='cuda:0')
tensor([[27.6259],
        [27.6259],
        [27.6259],
        ...,
        [27.6259],
        [27.6259],
        [27.6259]], device='cuda:0')
exact price:  tensor(4.9719, device='cuda:0')
Estimated price:  tensor(4.9718, device='cuda:0')
Estimated CI:  [4.971352577209473, 4.972330093383789]


In [22]:
from deep_kolmogorov import modeling, pdes, trainer
import torch
import numpy as np
import importlib
importlib.reload(trainer)
pde = pdes.MJDbasket()
import numpy as np
K = 1000
num_path = 1000
device = torch.device("cuda")
config_d = {"s":10, "sigma": 0.25, "m" : 0., "delta": 0.25}
config = {"r":0.0, "kappa": 0.5, "lambda":1, "rho_b": 0., "rho_j": -0.1}

import importlib
importlib.reload(pdes)
pde = pdes.MJDbasket()

with torch.no_grad():
    data = {
        key: torch.full(((K+1)*num_path, 1), value, dtype=torch.float32, device=device) for key, value in config.items()
    }
    data.update(
        {
        key: torch.full(((K+1)*num_path, 10), value, dtype=torch.float32, device=device) for key, value in config_d.items()
        }
    )
    data.update(
        {
            "t": torch.full((K + 1,), 0, dtype=torch.float32, device=device).repeat(num_path).reshape(-1,1)
        }
    )

data["x"] = data["s"]
data["K"] = pdes.MJDbasket.get_K(data)
payoff = pde.sde(data)

C0 = torch.mean(payoff)
cstd = torch.std(payoff)

print("exact price: ", (torch.exp(-data["t"]*data["r"]) * pde.solution(data))[0,0])
print("Estimated price: ", C0)
print("Estimated CI: ", f"[{C0 - 1.96*cstd/np.sqrt(K*num_path)}, {C0 + 1.96*cstd/np.sqrt(K*num_path)}]")

tensor([[-0.0317],
        [-0.0317],
        [-0.0317],
        ...,
        [-0.0317],
        [-0.0317],
        [-0.0317]], device='cuda:0')
tensor([[9.7227],
        [9.7227],
        [9.7227],
        ...,
        [9.7227],
        [9.7227],
        [9.7227]], device='cuda:0')
tensor([[8.0499],
        [8.0499],
        [8.0499],
        ...,
        [8.0499],
        [8.0499],
        [8.0499]], device='cuda:0')
tensor([[0.2500],
        [0.2500],
        [0.2500],
        ...,
        [0.2500],
        [0.2500],
        [0.2500]], device='cuda:0')

tensor([[5.],
        [5.],
        [5.],
        ...,
        [5.],
        [5.],
        [5.]], device='cuda:0')
tensor([[9.7227],
        [9.7227],
        [9.7227],
        ...,
        [9.7227],
        [9.7227],
        [9.7227]], device='cuda:0')
tensor([[-5.1613],
        [-5.1613],
        [-5.1613],
        ...,
        [-5.1613],
        [-5.1613],
        [-5.1613]], device='cuda:0')
tensor([[-5.1613],
        [-5.1613],
