In [1]:
from deep_kolmogorov import modeling, pdes, trainer
import torch

# model = modeling.KolmogorovNet(modeling.DeepONet(1,{"size_t_s_u": [1,1,3], "num_depth" : 6, "num_width" : 55}), pdes.BSr())
# path = "./exp/avg_bs_r_2023_10_02_00_58_02/Trainer_2023-10-02_00-58-02/Trainer_aed00_00005_5_num_depth=6,num_width=55,seed=0_2023-10-02_00-58-02/checkpoint_000030"
# model.net.load_state_dict(torch.load(f"{path}/model.pth", map_location=torch.device('cuda')))

In [2]:
config={
  "bs": 120000,
  "checkpoint": True,
  "factor": 6,
  "gpus": 1,
  "levels": 4,
  "lr": 0.01,
  "lr_decay": 0.25,
  "lr_decay_patience": 2,
  "min_lr": 1e-08,
  "mode": "avg_bs_r",
  "n_iterations": 30,
  "n_test_batches": 1,
  "n_train_batches": 2000,
  "net": "DeepONet",
  "norm_layer": "layernorm",
  "num_depth": 7,
  "num_width": 75,
  "opt": "adamw",
  "pde": "BSr",
  "seed": 0,
  "size_t_x_u": [
    1,
    1,
    3
  ],
  "unfreeze": "all",
  "unfreeze_patience": 1,
  "weight_decay": 0.01
}

mytrainer = trainer.Trainer(config)
path = "/home/ycui/Documents/my_deepkol/exp/avg_bs_r_2023_11_08_21_47_16/Trainer_2023-11-08_21-47-16/Trainer_5467d_00005_5_num_depth=7,num_width=75,seed=0_2023-11-08_21-47-16/checkpoint_000023/model.pth"
mytrainer.load_checkpoint(path)


/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/trainable/trainable.py:1080: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
`UnifiedLogger` will be removed in Ray 2.7.
  self._result_logger = UnifiedLogger(config, self._logdir, loggers=None)
/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API

Caught type mismatch error: converting model to float64


2024-06-04 17:10:15,336	INFO trainable.py:172 -- Trainable.setup took 11.109 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.


In [5]:
scores_test = mytrainer._test_greeks_loop(greeks=[ "vega"], method="finidiff", d= 0.05)
scores_test["vega"]["current"]

{'time': 0.06530189514160156,
 'steps': 1,
 'overall time': 0.06530189514160156,
 'overall steps': 1.0,
 'mse': 0.06663250838800078,
 'L2^2': 0.024186009733236553,
 'mae': 0.1636622700419169,
 'L1': 0.07795560929198284,
 'L1_std': 0.13456999525732063,
 'L2': 0.1555185189398245}

In [6]:
scores_test = mytrainer._test_greeks_loop(greeks=["delta"], method="finidiff", d= 0.05)
scores_test["delta"]["current"]

{'time': 0.06126594543457031,
 'steps': 1,
 'overall time': 0.06126594543457031,
 'overall steps': 1.0,
 'mse': 0.00023693440487017575,
 'L2^2': 0.00010953145625760573,
 'mae': 0.008160906618203175,
 'L1': 0.0053690676121811555,
 'L1_std': 0.008983609618786914,
 'L2': 0.010465727698426217}

In [7]:
scores_test = mytrainer._test_greeks_loop(greeks=["delta", "vega"], method="autodiff")
scores_test["vega"]["current"]

{'time': 0.13860440254211426,
 'steps': 1,
 'overall time': 0.13860440254211426,
 'overall steps': 1.0,
 'mse': 0.15848860620935729,
 'L2^2': 0.056949697047118525,
 'mae': 0.244168530623087,
 'L1': 0.11262497426149749,
 'L1_std': 0.21039410900374542,
 'L2': 0.23864135653134083}

In [8]:
scores_test["delta"]["current"]

{'time': 0.1385951042175293,
 'steps': 1,
 'overall time': 0.1385951042175293,
 'overall steps': 1.0,
 'mse': 0.0020741650429414327,
 'L2^2': 0.0008488886792687748,
 'mae': 0.02743378595209106,
 'L1': 0.017785596280828847,
 'L1_std': 0.023077384650128797,
 'L2': 0.029135694247242074}

In [27]:
mytrainer.test_loader = mytrainer.pde.dataloader(120000, 1, 'test')

In [ ]:
mytrainer.pde.get_greeks

# Test greeks under 10D geometric european call option

In [2]:
config = {
  "bs": 120000,
  "checkpoint": True,
  "factor": 6,
  "gpus": 1,
  "levels": 4,
  "lr": 0.01,
  "lr_decay": 0.25,
  "lr_decay_patience": 2,
  "min_lr": 1e-08,
  "mode": "avg_bs_basket",
  "n_iterations": 30,
  "n_test_batches": 1,
  "n_train_batches": 2000,
  "net": "DeepONet",
  "norm_layer": "layernorm",
  "num_depth": 7,
  "num_width": 75,
  "opt": "adamw",
  "pde": "BSbasket",
  "seed": 0,
  "size_t_x_u": [
    1,
    10,
    13
  ],
  "unfreeze": "all",
  "unfreeze_patience": 1,
  "weight_decay": 0.01
}

mytrainer = trainer.Trainer(config)
path = "/home/ycui/Documents/my_deepkol/exp/avg_bs_basket_2023_10_31_17_27_14/Trainer_2023-10-31_17-27-14/Trainer_ad10d_00005_5_num_depth=7,num_width=75,seed=0_2023-10-31_17-27-14/checkpoint_000016/model.pth"
# mytrainer.net.PI_layers(torch.randn(1,10,1, device=torch.device("cuda"))) # add it when loading checkpoint with the input shape same as the experiment
mytrainer.load_checkpoint(path)

/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/trainable/trainable.py:1080: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
`UnifiedLogger` will be removed in Ray 2.7.
  self._result_logger = UnifiedLogger(config, self._logdir, loggers=None)
/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/ycui/.conda/envs/torch/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API

Caught type mismatch error: converting model to float64


2024-06-04 17:22:20,812	INFO trainable.py:172 -- Trainable.setup took 12.554 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.


In [3]:
scores_test = mytrainer._test_greeks_loop(greeks=[ "vega"], method="finidiff", d= 0.05)
scores_test["vega"]["current"]

{'time': 0.5853750705718994,
 'steps': 1,
 'overall time': 0.5853750705718994,
 'overall steps': 1.0,
 'mse': 0.000769342554543244,
 'L2^2': 0.0006217582798051552,
 'mae': 0.0186287502836025,
 'L1': 0.01691558497738497,
 'L1_std': 0.01831997664753253,
 'L2': 0.024935081307370047}

In [4]:
scores_test = mytrainer._test_greeks_loop(greeks=["delta"], method="finidiff", d= 0.05)
scores_test["delta"]["current"]

{'time': 0.6096150875091553,
 'steps': 1,
 'overall time': 0.6096150875091553,
 'overall steps': 1.0,
 'mse': 2.602380434195674e-05,
 'L2^2': 2.1744173834481935e-05,
 'mae': 0.0032216021348198225,
 'L1': 0.003012107384185815,
 'L1_std': 0.003559690084867918,
 'L2': 0.004663064854200715}

In [5]:
scores_test = mytrainer._test_greeks_loop(greeks=["delta", "vega", "c-delta"], method="autodiff")
scores_test["vega"]["current"]

{'time': 1.3723015785217285,
 'steps': 1,
 'overall time': 1.3723015785217285,
 'overall steps': 1.0,
 'mse': 0.000818330765299869,
 'L2^2': 0.0006639450476336831,
 'mae': 0.019311304752804476,
 'L1': 0.017547229170217303,
 'L1_std': 0.01886902469093235,
 'L2': 0.02576713114868792}

In [6]:
scores_test["delta"]["current"]

{'time': 1.3722777366638184,
 'steps': 1,
 'overall time': 1.3722777366638184,
 'overall steps': 1.0,
 'mse': 4.796065493100127e-05,
 'L2^2': 4.044489596438815e-05,
 'mae': 0.0042708801165736035,
 'L1': 0.003992812700425873,
 'L1_std': 0.0049499861739868666,
 'L2': 0.006359630175127179}

In [7]:
scores_test["c-delta"]["current"]

{'time': 1.3723108768463135,
 'steps': 1,
 'overall time': 1.3723108768463135,
 'overall steps': 1.0,
 'mse': 0.014664163792788683,
 'L2^2': 0.00520346619192455,
 'mae': 0.06842693761482203,
 'L1': 0.042292361967333075,
 'L1_std': 0.058436724484486766,
 'L2': 0.07213505522230194}

In [11]:
res = mytrainer.model.module.test_greeks(batch, greeks=["delta", "vega", "c-delta"], method="autodiff", d=0.001)

In [19]:
_greek = "vega"
((res["pde"][_greek] - res["net"][_greek]).abs()/(res["pde"][_greek]+1)).mean(dim=0)

tensor([0.0182, 0.0194, 0.0177, 0.0196, 0.0180, 0.0180, 0.0191, 0.0187, 0.0214,
        0.0189], device='cuda:0')

In [16]:
res["net"]["delta"]

tensor([[0.0112, 0.0103, 0.0097,  ..., 0.0095, 0.0102, 0.0079],
        [0.0720, 0.0767, 0.1099,  ..., 0.0958, 0.0703, 0.0815],
        [0.1188, 0.1245, 0.1071,  ..., 0.0898, 0.1081, 0.0764],
        ...,
        [0.0135, 0.0142, 0.0189,  ..., 0.0149, 0.0198, 0.0194],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0105, 0.0161, 0.0056,  ..., 0.0075, 0.0074, 0.0073]],
       device='cuda:0')

In [3]:
with torch.no_grad():
    device = next(mytrainer.net.parameters()).device  # 获取模型所在的设备
    batch = {k: v.to(device) for k, v in batch.items()}  # 将 batch 中的所有数据移动到相同设备
    resopt = mytrainer.model.module.forward(batch, train=False)

NameError: name 'batch' is not defined

In [28]:
((resopt["pde"] - resopt["net"]).abs()/(resopt["pde"]+1)).mean(dim=0)

tensor([0.0039], device='cuda:0')

## test the step size under 1D eucall

In [5]:
for batch in mytrainer.test_loader:
    pass

In [10]:
param = "vega"

g = {
    f"greeks{d}": pdes.Pde.get_greeks(mytrainer.pde, batch, greeks=[param], d=d) for d in [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8]
}
bench = mytrainer.pde.get_greeks(batch, greeks=[param], d=1e-8)
for _e, _g in g.items():
    print(f"error of {_e} is ")
    print((_g[param]-bench[param]).abs().mean())

error of greeks0.1 is 
tensor(0.0014, dtype=torch.float64)
error of greeks0.01 is 
tensor(0.0001, dtype=torch.float64)
error of greeks0.001 is 
tensor(1.2300e-05, dtype=torch.float64)
error of greeks0.0001 is 
tensor(1.2293e-06, dtype=torch.float64)
error of greeks1e-05 is 
tensor(1.2495e-07, dtype=torch.float64)
error of greeks1e-06 is 
tensor(1.9672e-08, dtype=torch.float64)
error of greeks1e-07 is 
tensor(1.7318e-08, dtype=torch.float64)
error of greeks1e-08 is 
tensor(1.2502e-07, dtype=torch.float64)


In [6]:
G = mytrainer.pde.get_greeks(batch, greeks=["delta","vega"])
print("the mean of delta is")
print(G["delta"].mean())
print("the mean of vega is")
print(G["vega"].mean())

the mean of delta is
tensor(0.0501, dtype=torch.float64)
the mean of vega is
tensor(0.0464, dtype=torch.float64)


tensor([[2.2151e-05, 1.8921e-05, 3.0895e-05,  ..., 2.4464e-05, 7.2530e-05,
         2.1203e-05],
        [9.5587e-02, 9.0372e-02, 8.5417e-02,  ..., 1.1294e-01, 1.0858e-01,
         9.4049e-02],
        [1.5446e-03, 3.8066e-03, 1.8478e-03,  ..., 2.7395e-03, 1.7675e-03,
         2.8333e-03],
        ...,
        [7.4857e-02, 9.9304e-02, 8.6928e-02,  ..., 8.0473e-02, 8.2726e-02,
         1.0132e-01],
        [7.5719e-02, 1.1150e-01, 1.0946e-01,  ..., 9.3749e-02, 1.1988e-01,
         1.8563e-01],
        [1.3325e-02, 6.9516e-03, 9.2796e-03,  ..., 8.3262e-03, 9.9603e-03,
         9.3493e-03]], dtype=torch.float64)

In [13]:
G["vega"]

tensor([[ 1.8168e-04,  1.8053e-04,  1.9668e-04,  ...,  1.8042e-04,
          2.0153e-04,  1.9304e-04],
        [ 6.0720e-02,  5.3860e-02,  2.7715e-02,  ...,  3.4986e-02,
         -6.7871e-02,  1.1145e-02],
        [ 6.6853e-03,  9.2885e-03,  6.8636e-03,  ...,  6.0642e-03,
          5.2950e-03,  6.5865e-03],
        ...,
        [-1.6751e-01, -1.8771e-01, -4.9960e-02,  ..., -4.5409e-02,
         -1.6320e-01, -2.3672e-01],
        [-3.5325e-02, -5.2938e-02, -5.1957e-02,  ..., -3.7986e-02,
         -1.2233e-02, -2.3900e-02],
        [ 5.2087e-02,  5.7469e-02,  5.2319e-02,  ...,  5.6784e-02,
          5.2742e-02,  5.6436e-02]], dtype=torch.float64)